# ======= mlflow.yaml =======
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-deployment
  namespace: ml
  labels:
    app: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:

      serviceAccountName: ml-service-account
      
      containers:
        - name: mlflow
          image: gcr.io/gen-lang-client-0202545123/mlflow-server:$SHORT_SHA
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: MLFLOW_BACKEND_STORE_URI
              valueFrom:
                secretKeyRef:
                  name: secrets-1
                  key: POSTGRESQL_URI
            - name: MLFLOW_ARTIFACT_ROOT
              valueFrom:
                configMapKeyRef:
                  name: confmap-1
                  key: BUCKET_3
            - name: WERKZEUG_DEBUG
              value: "false"
            - name: MLFLOW_DISABLE_HOST_CHECK
              value: "true"
            - name: FLASK_ENV
              value: "production"
            - name: GUNICORN_CMD_ARGS
              value: "--timeout 120 --workers 2 --forwarded-allow-ips='*'"
            - name: MLFLOW_SERVER_ALLOWED_HOSTS
              value: "*"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            # limits:
            #   memory: "256Mi"
            #   cpu: "300m"
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
  namespace: ml
  labels:
    app: mlflow
spec:
  type: LoadBalancer
  selector:
    app: mlflow
  ports:
    - name: http
      port: 80
      targetPort: 5000
