steps:
- name: 'ubuntu'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "DEBUG: REGION=$_REGION"
      echo "DEBUG: CLUSTER=$_CLUSTER"

- name: 'gcr.io/cloud-builders/docker'
  id: Build DB App Image
  args:
    [
      'build',
      '-t', 'gcr.io/gen-lang-client-0202545123/dbapp:$SHORT_SHA',
      '.'
    ]
  dir: 'dbapp'

- name: 'gcr.io/cloud-builders/docker'
  id: Build ML App Image
  args:
    [
      'build',
      '-t', 'gcr.io/gen-lang-client-0202545123/mlapp:$SHORT_SHA',
      '.'
    ]
  dir: 'mlapp'

- name: 'gcr.io/cloud-builders/docker'
  id: Build Web App Image
  args:
    [
      'build',
      '-t', 'gcr.io/gen-lang-client-0202545123/webapp:$SHORT_SHA',
      '.'
    ]
  dir: 'webapp'


# -------------------------------------------------------------
# 2️⃣ Push images to GCR
# -------------------------------------------------------------
- name: 'gcr.io/cloud-builders/docker'
  id: Push DB App Image
  args: ['push', 'gcr.io/gen-lang-client-0202545123/dbapp:$SHORT_SHA']

- name: 'gcr.io/cloud-builders/docker'
  id: Push ML App Image
  args: ['push', 'gcr.io/gen-lang-client-0202545123/mlapp:$SHORT_SHA']

- name: 'gcr.io/cloud-builders/docker'
  id: Push Web App Image
  args: ['push', 'gcr.io/gen-lang-client-0202545123/webapp:$SHORT_SHA']


# -------------------------------------------------------------
# 3️⃣ Apply Kubernetes manifests for orchestration
# -------------------------------------------------------------
- name: 'gcr.io/cloud-builders/kubectl'
  id: Apply ConfigMap 2
  args: ['apply', '-f', 'k8s_web/confmap_2.yaml']
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=$_REGION'
    - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER'


- name: gcr.io/cloud-builders/kubectl
  id: Apply ServiceAccount
  env:
    - CLOUDSDK_COMPUTE_ZONE=$_REGION
    - CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER
  args:
    - apply
    - '-f'
    - k8s_web/ksa.yaml

- name: 'gcr.io/cloud-builders/gcloud'
  id: Apply DB App Deployment
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      apt-get update && apt-get install -y gettext-base
      export SHORT_SHA=$SHORT_SHA
      envsubst < k8s_web/dbapp.yaml | kubectl apply -f -
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=$_REGION'
    - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER'

- name: 'gcr.io/cloud-builders/gcloud'
  id: Apply ML App Deployment
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      apt-get update && apt-get install -y gettext-base
      export SHORT_SHA=$SHORT_SHA
      envsubst < k8s_web/mlapp.yaml | kubectl apply -f -
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=$_REGION'
    - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER'

- name: 'gcr.io/cloud-builders/gcloud'
  id: Apply Web App Deployment
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      apt-get update && apt-get install -y gettext-base
      export SHORT_SHA=$SHORT_SHA
      envsubst < k8s_web/webapp.yaml | kubectl apply -f -
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=$_REGION'
    - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER'



###############################################################################

# Delete existing CronJob to ensure clean deployment
- name: gcr.io/cloud-builders/gcloud
  id: Delete Old CRONJOB for restart-mlapp
  entrypoint: bash
  env:
    - CLOUDSDK_COMPUTE_ZONE=$_REGION
    - CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER
  args:
    - '-c'
    - |
      kubectl delete cronjob restart-mlapp -n web --ignore-not-found=true
      echo "Old CronJob deleted (if it existed)"


- name: gcr.io/cloud-builders/gcloud
  id: Apply CRONJOB Deployment for restart-mlapp
  entrypoint: bash
  env:
    - CLOUDSDK_COMPUTE_ZONE=$_REGION
    - CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER
  args:
    - '-c'
    - |
      kubectl apply -f k8s_web/restart-mlapp.yaml


###############################################################################

# -------------------------------------------------------------
# 4️⃣ Prometheus Monitoring Setup
# -------------------------------------------------------------
- name: 'gcr.io/cloud-builders/kubectl'
  id: Apply Prometheus ConfigMap
  args: ['apply', '-f', 'k8s_web/prometheus-configmap.yaml']
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=$_REGION'
    - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER'

- name: 'gcr.io/cloud-builders/kubectl'
  id: Apply Prometheus Deployment
  args: ['apply', '-f', 'k8s_web/prometheus-deployment.yaml']
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=$_REGION'
    - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER'

- name: 'gcr.io/cloud-builders/kubectl'
  id: Apply Prometheus Service
  args: ['apply', '-f', 'k8s_web/prometheus-service.yaml']
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=$_REGION'
    - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER'

# -------------------------------------------------------------
# 5️⃣ Apply Ingress for public routing
# -------------------------------------------------------------
- name: 'gcr.io/cloud-builders/kubectl'
  id: Apply Ingress
  args: ['apply', '-f', 'k8s_web/ingress.yaml']
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=$_REGION'
    - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER'


# -------------------------------------------------------------
# 6️⃣ Verify Deployment Status
# -------------------------------------------------------------
- name: 'gcr.io/cloud-builders/kubectl'
  id: Verify Pods
  args:
    - 'get'
    - 'pods'
    - '--namespace=web'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=$_REGION'
    - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER'


# -------------------------------------------------------------
# 🧩 Substitutions
# -------------------------------------------------------------
substitutions:
  _REGION: us-central1-a        # change this to your GKE region or zone
  _CLUSTER: mlops-cluster    # change this to your actual cluster name


# ------------------------------------------------------------
# 💾 Image tracking (build outputs)
# -------------------------------------------------------------
images:
  - 'gcr.io/gen-lang-client-0202545123/dbapp:$SHORT_SHA'
  - 'gcr.io/gen-lang-client-0202545123/mlapp:$SHORT_SHA'
  - 'gcr.io/gen-lang-client-0202545123/webapp:$SHORT_SHA'

options:
 logging: CLOUD_LOGGING_ONLY