steps:
  - name: ubuntu
    entrypoint: bash
    args:
      - '-c'
      - |
        echo "DEBUG: REGION=$_REGION"
        echo "DEBUG: CLUSTER=$_CLUSTER"
  - name: gcr.io/cloud-builders/docker
    id: Build Linear Regression Image
    dir: models/linear_regression
    args:
      - build
      - '-t'
      - 'gcr.io/gen-lang-client-0202545123/linear_regression:$SHORT_SHA'
      - .
  - name: gcr.io/cloud-builders/docker
    id: Build Data Cronjob Image
    dir: data_collection_and_versioning
    args:
      - build
      - '-t'
      - 'gcr.io/gen-lang-client-0202545123/ml-cronjob:$SHORT_SHA'
      - .
  - name: gcr.io/cloud-builders/docker
    id: Build MLflow Image
    dir: mlflow
    args:
      - build
      - '-t'
      - 'gcr.io/gen-lang-client-0202545123/mlflow-server:$SHORT_SHA'
      - .
  - name: gcr.io/cloud-builders/docker
    id: Push Linear Regression Image
    args:
      - push
      - 'gcr.io/gen-lang-client-0202545123/linear_regression:$SHORT_SHA'
  - name: gcr.io/cloud-builders/docker
    id: Push Data Cronjob Image
    args:
      - push
      - 'gcr.io/gen-lang-client-0202545123/ml-cronjob:$SHORT_SHA'
  - name: gcr.io/cloud-builders/docker
    id: Push MLflow Image
    args:
      - push
      - 'gcr.io/gen-lang-client-0202545123/mlflow-server:$SHORT_SHA'
  - name: gcr.io/cloud-builders/kubectl
    id: Apply ConfigMap
    env:
      - CLOUDSDK_COMPUTE_ZONE=$_REGION
      - CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER
    args:
      - apply
      - '-f'
      - k8s_ml/confmap_1.yaml
  - name: gcr.io/cloud-builders/kubectl
    id: Apply ServiceAccount
    env:
      - CLOUDSDK_COMPUTE_ZONE=$_REGION
      - CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER
    args:
      - apply
      - '-f'
      - k8s_ml/ksa.yaml

################################################################################



# Delete existing CronJob to ensure clean deployment
  - name: gcr.io/cloud-builders/gcloud
    id: Delete Old CRONJOB
    entrypoint: bash
    env:
      - CLOUDSDK_COMPUTE_ZONE=$_REGION
      - CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER
    args:
      - '-c'
      - |
        kubectl delete cronjob ml-cronjob -n ml --ignore-not-found=true
        echo "Old CronJob deleted (if it existed)"



# sed command wins but with the other variable name -- hehe this works now :)
  - name: gcr.io/cloud-builders/gcloud
    id: Apply CRONJOB Deployment
    entrypoint: bash
    env:
      - CLOUDSDK_COMPUTE_ZONE=$_REGION
      - CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y gettext-base
        echo $SHORT_SHA
        export SHORT_SHA=$SHORT_SHA
        sed "s|__THIS__IS__MY__VARIABLE__|$SHORT_SHA|g" k8s_ml/cronjob.yaml
        sed "s|__THIS__IS__MY__VARIABLE__|$SHORT_SHA|g" k8s_ml/cronjob.yaml | kubectl apply -f -



##############################################################################


# Delete existing CronJob to ensure clean deployment
  - name: gcr.io/cloud-builders/gcloud
    id: Delete Old Linear Regression CRONJOB
    entrypoint: bash
    env:
      - CLOUDSDK_COMPUTE_ZONE=$_REGION
      - CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER
    args:
      - '-c'
      - |
        kubectl delete cronjob linear-regression -n ml --ignore-not-found=true
        echo "Old CronJob deleted (if it existed)"



# sed command wins but with the other variable name -- hehe this works now :)
  - name: gcr.io/cloud-builders/gcloud
    id: Apply CRONJOB Deployment for Linear Regression
    entrypoint: bash
    env:
      - CLOUDSDK_COMPUTE_ZONE=$_REGION
      - CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y gettext-base
        echo $SHORT_SHA
        export SHORT_SHA=$SHORT_SHA
        sed "s|__THIS__IS__MY__VARIABLE__|$SHORT_SHA|g" k8s_ml/linear_regression.yaml
        sed "s|__THIS__IS__MY__VARIABLE__|$SHORT_SHA|g" k8s_ml/linear_regression.yaml | kubectl apply -f -



###############################################################################

  - name: gcr.io/cloud-builders/gcloud
    id: Apply MLflow Deployment
    entrypoint: bash
    env:
      - CLOUDSDK_COMPUTE_ZONE=$_REGION
      - CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y gettext-base
        export SHORT_SHA=$SHORT_SHA
        envsubst < k8s_ml/mlflow.yaml | kubectl apply -f -
  - name: gcr.io/cloud-builders/kubectl
    id: Apply mlflow-ingress
    env:
      - CLOUDSDK_COMPUTE_ZONE=$_REGION
      - CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER
    args:
      - apply
      - '-f'
      - k8s_ml/mlflow-ingress.yaml
images:
  - 'gcr.io/gen-lang-client-0202545123/linear_regression:$SHORT_SHA'
  - 'gcr.io/gen-lang-client-0202545123/ml-cronjob:$SHORT_SHA'
  - 'gcr.io/gen-lang-client-0202545123/mlflow-server:$SHORT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _REGION: us-central1-a
  _CLUSTER: mlops-cluster