apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbapp-deployment
  namespace: web
  labels:
    app: dbapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbapp
  template:
    metadata:
      labels:
        app: dbapp
    spec:
      containers:
        - name: dbapp
          image: gcr.io/gen-lang-client-0202545123/dbapp:$SHORT_SHA
          imagePullPolicy: Always
          ports:
            - containerPort: 5002
          env:
            # Load from ConfigMap
            - name: MONGO_DB
              valueFrom:
                configMapKeyRef:
                  name: confmap-2
                  key: MONGO_DB
            - name: COLLECTION_1
              valueFrom:
                configMapKeyRef:
                  name: confmap-2
                  key: COLLECTION_1
            - name: COLLECTION_2
              valueFrom:
                configMapKeyRef:
                  name: confmap-2
                  key: COLLECTION_2
            # Load from Secret
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: secrets-2
                  key: MONGO_URI
          resources:
            requests:
              cpu: "50m"    # Reduced from 100m
              memory: "64Mi" # Reduced from 128Mi
            # limits:
            #   cpu: "200m"    # Reduced from 500m
            #   memory: "128Mi" # Reduced from 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: dbapp
  namespace: web
  labels:
    app: dbapp
spec:
  type: ClusterIP
  selector:
    app: dbapp
  ports:
    - name: http
      port: 80          # Exposed inside the cluster
      targetPort: 5002  # Container port
