# 1️⃣ Create the KSA
apiVersion: v1
kind: ServiceAccount
metadata:
  name: web-service-account
  namespace: web
  annotations:
    iam.gke.io/gcp-service-account: mlops-500@gen-lang-client-0202545123.iam.gserviceaccount.com
---
# 2️⃣ Give it RBAC rights
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-restart-role
  namespace: web
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-restart-binding
  namespace: web
subjects:
  - kind: ServiceAccount
    name: web-service-account
    namespace: web
roleRef:
  kind: Role
  name: deployment-restart-role
  apiGroup: rbac.authorization.k8s.io
