apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: web
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: gcr.io/gen-lang-client-0202545123/webapp:$SHORT_SHA
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            # limits:
            #   cpu: "150m"
          # env:
          #   - name: ENV
          #     value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: web
  labels:
    app: webapp
spec:
  type: ClusterIP
  selector:
    app: webapp
  ports:
    - name: http
      port: 80          # Exposed inside the cluster
      targetPort: 5000  # Maps to containerPort
